### ISSUE TITLE
Can we discover TF files in the current working directory by default?

### ISSUE THREAD

**Issue by e-gineer** [turbot/steampipe-plugin-terraform#6]
Terraform users are used to the idea of running TF commands in the current working directory for their files. It's inconvenient and unintuitive that we require the `paths` to be configured first. Can we discover files in the current working directory by default?

The obvious snag is operation when in service mode - we'd need to think about that a bit more carefully as part of this.

**Comment by cbruno10** [comment]
@e-gineer I like this approach, and we could use it similar plugins like CSV, Code (for INI, YML, etc.). We actually had started a similar change in https://github.com/turbot/steampipe-plugin-csv/pull/12, though it was incomplete and did not lean into setting the default of `paths` to the current working directory, which I think is a reasonable approach.

If we do set the default to something like:
```
connection "terraform" {
  plugin = "terraform"

  # Paths is a list of locations to search for Terraform configuration files.
  # Wildcards are supported per https://golang.org/pkg/path/filepath/#Match
  # Exact file paths can have any name. Wildcard based matches must have an
  # extension of .tf (case insensitive).
  paths = [ "." ]
}
```

Then I think the plugin should warn if `paths` is not set (since that would be a deliberate change from the default) and fail to initialize. This would give users proper warning so they can adjust their config file afterward.

If running in service mode, would you expect errors, or just no files loaded?
